name = "books_api"
version = "1.0.0"
description = "Self-hosted books library API server built with Gleam and Wisp"
licences = ["MIT"]

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
sqlight = ">= 1.0.1 and < 2.0.0"
cors_builder = ">= 2.0.5 and < 3.0.0"
mist = ">= 5.0.1 and < 6.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
